on: 
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:
  push:
  # pull_request: # Run this action when push event triggers.
    branches: # Run this action on specified branches
      - develop
      - add/CI
      - add/gh-action-for-codeception

name: Run Codeception test cases # Name of the action
jobs:
  Run-wpe2e-TestCase:
    name: Run Codeception test Case #
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
       ref: ${{ github.event.pull_request.head.sha }}
     
    - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
      uses: browserstack/github-actions/setup-env@master
      with:
        username:  ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        build-name: 'BUILD_INFO'
        project-name: 'REPO_NAME'

    - name: Current directory and listings
      run: |
           pwd
           ls -al
    - name: Install and config site
      uses: docker://rtcamp/base-wo:v1.0.0
      env:
        RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
   
   


